# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6b578b81f33a3cba0dff61a8798e9336fe9d3332b65ad13b5cf49316a5bc7e6c50b22009418a1fd5774e36f88029bcff50f986227c32789719d5bba40151e6e

test:
  secret_key_base: a1c42b31b4b645ecee11c8c9d013ae01640dd5ee0d2d851ac03f0ed5939e4d097d78d091e53398edce449e4c63f43e0af41eaa91d5496408b855998bd2d3a5e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
